/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SampleChapterRouteImport } from './routes/sample-chapter'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MediaRouteImport } from './routes/media'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginBuyerRouteImport } from './routes/login/buyer'
import { Route as LoginAuthorRouteImport } from './routes/login/author'
import { Route as LoginAdminRouteImport } from './routes/login/admin'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard/buyer'
import { Route as DashboardAuthorRouteImport } from './routes/dashboard/author'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleChapterRoute = SampleChapterRouteImport.update({
  id: '/sample-chapter',
  path: '/sample-chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginBuyerRoute = LoginBuyerRouteImport.update({
  id: '/login/buyer',
  path: '/login/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAuthorRoute = LoginAuthorRouteImport.update({
  id: '/login/author',
  path: '/login/author',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthorRoute = DashboardAuthorRouteImport.update({
  id: '/dashboard/author',
  path: '/dashboard/author',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/buy': typeof BuyRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/sample-chapter': typeof SampleChapterRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/author': typeof LoginAuthorRoute
  '/login/buyer': typeof LoginBuyerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/buy': typeof BuyRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/sample-chapter': typeof SampleChapterRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/author': typeof LoginAuthorRoute
  '/login/buyer': typeof LoginBuyerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/buy': typeof BuyRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/sample-chapter': typeof SampleChapterRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/author': typeof LoginAuthorRoute
  '/login/buyer': typeof LoginBuyerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/author'
    | '/book'
    | '/buy'
    | '/checkout'
    | '/contact'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/sample-chapter'
    | '/signup'
    | '/sitemap.xml'
    | '/speaking'
    | '/terms'
    | '/workshops'
    | '/dashboard/admin'
    | '/dashboard/author'
    | '/dashboard/buyer'
    | '/login/admin'
    | '/login/author'
    | '/login/buyer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/articles'
    | '/author'
    | '/book'
    | '/buy'
    | '/checkout'
    | '/contact'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/sample-chapter'
    | '/signup'
    | '/sitemap.xml'
    | '/speaking'
    | '/terms'
    | '/workshops'
    | '/dashboard/admin'
    | '/dashboard/author'
    | '/dashboard/buyer'
    | '/login/admin'
    | '/login/author'
    | '/login/buyer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/author'
    | '/book'
    | '/buy'
    | '/checkout'
    | '/contact'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/sample-chapter'
    | '/signup'
    | '/sitemap.xml'
    | '/speaking'
    | '/terms'
    | '/workshops'
    | '/dashboard/admin'
    | '/dashboard/author'
    | '/dashboard/buyer'
    | '/login/admin'
    | '/login/author'
    | '/login/buyer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArticlesRoute: typeof ArticlesRoute
  AuthorRoute: typeof AuthorRoute
  BookRoute: typeof BookRoute
  BuyRoute: typeof BuyRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  MediaRoute: typeof MediaRoute
  PrivacyRoute: typeof PrivacyRoute
  SampleChapterRoute: typeof SampleChapterRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakingRoute: typeof SpeakingRoute
  TermsRoute: typeof TermsRoute
  WorkshopsRoute: typeof WorkshopsRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAuthorRoute: typeof DashboardAuthorRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginAuthorRoute: typeof LoginAuthorRoute
  LoginBuyerRoute: typeof LoginBuyerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-chapter': {
      id: '/sample-chapter'
      path: '/sample-chapter'
      fullPath: '/sample-chapter'
      preLoaderRoute: typeof SampleChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/buyer': {
      id: '/login/buyer'
      path: '/login/buyer'
      fullPath: '/login/buyer'
      preLoaderRoute: typeof LoginBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/author': {
      id: '/login/author'
      path: '/login/author'
      fullPath: '/login/author'
      preLoaderRoute: typeof LoginAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/author': {
      id: '/dashboard/author'
      path: '/dashboard/author'
      fullPath: '/dashboard/author'
      preLoaderRoute: typeof DashboardAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArticlesRoute: ArticlesRoute,
  AuthorRoute: AuthorRoute,
  BookRoute: BookRoute,
  BuyRoute: BuyRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  MediaRoute: MediaRoute,
  PrivacyRoute: PrivacyRoute,
  SampleChapterRoute: SampleChapterRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakingRoute: SpeakingRoute,
  TermsRoute: TermsRoute,
  WorkshopsRoute: WorkshopsRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAuthorRoute: DashboardAuthorRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginAuthorRoute: LoginAuthorRoute,
  LoginBuyerRoute: LoginBuyerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
