/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SampleChapterRouteImport } from './routes/sample-chapter'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MediaRouteImport } from './routes/media'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleChapterRoute = SampleChapterRouteImport.update({
  id: '/sample-chapter',
  path: '/sample-chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/sample-chapter': typeof SampleChapterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/sample-chapter': typeof SampleChapterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/sample-chapter': typeof SampleChapterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/author'
    | '/book'
    | '/buy'
    | '/contact'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/sample-chapter'
    | '/sitemap.xml'
    | '/speaking'
    | '/workshops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/author'
    | '/book'
    | '/buy'
    | '/contact'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/sample-chapter'
    | '/sitemap.xml'
    | '/speaking'
    | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/author'
    | '/book'
    | '/buy'
    | '/contact'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/sample-chapter'
    | '/sitemap.xml'
    | '/speaking'
    | '/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  AuthorRoute: typeof AuthorRoute
  BookRoute: typeof BookRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  MediaRoute: typeof MediaRoute
  PrivacyRoute: typeof PrivacyRoute
  SampleChapterRoute: typeof SampleChapterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakingRoute: typeof SpeakingRoute
  WorkshopsRoute: typeof WorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-chapter': {
      id: '/sample-chapter'
      path: '/sample-chapter'
      fullPath: '/sample-chapter'
      preLoaderRoute: typeof SampleChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  AuthorRoute: AuthorRoute,
  BookRoute: BookRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  MediaRoute: MediaRoute,
  PrivacyRoute: PrivacyRoute,
  SampleChapterRoute: SampleChapterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakingRoute: SpeakingRoute,
  WorkshopsRoute: WorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
